name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace token placeholder
      run: sed -i 's/YOUR_GITHUB_TOKEN/${{ secrets.GH_TOKEN }}/' assets/js/loadRepos.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Directory to publish (root directory if no build process)
